version: '3.8'

services:
  db:
    image: postgres:16
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    command: ["go", "run", "./cmd/main.go"]

volumes:
  pgdata:
